"""initial world state schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 15:50:32.816598
"""
from alembic import op
import sqlalchemy as sa
import backend.app.repositories.sql.tables


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('canonical_attributes', sa.JSON(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('anchor', sa.String(length=128), nullable=True),
    sa.Column('current_state', sa.JSON(), nullable=False),
    sa.Column('attribute_statuses', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('observed_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('freshness_policies', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('history_refs', sa.JSON(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_anchor'), ['anchor'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_type'), ['type'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('timestamp', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('relation_id', sa.String(length=128), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.String(length=256), nullable=False),
    sa.Column('timestamp', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('authority', sa.Float(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('retention_policy', sa.String(length=64), nullable=True),
    sa.Column('integrity_reference', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_source_reference'), ['source_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_timestamp'), ['timestamp'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('timestamp', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('raw_reference', sa.Text(), nullable=True),
    sa.Column('observed_entities', sa.JSON(), nullable=False),
    sa.Column('spatial_context', sa.JSON(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('authority', sa.Float(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_timestamp'), ['timestamp'], unique=False)

    op.create_table('relations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('source_entity', sa.String(length=128), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity', sa.String(length=128), nullable=False),
    sa.Column('valid_from', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('valid_to', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relations_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_source_entity'), ['source_entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_target_entity'), ['target_entity'], unique=False)

    op.create_table('search_coverage',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('timestamp', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('visibility_conditions', sa.JSON(), nullable=False),
    sa.Column('searched_for', sa.JSON(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_coverage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_coverage_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_coverage_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_coverage_timestamp'), ['timestamp'], unique=False)

    op.create_table('state_versions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('attribute', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('valid_from', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('valid_to', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True),
    sa.Column('supported_by', sa.JSON(), nullable=False),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('state_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_versions_attribute'), ['attribute'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_versions_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_versions_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_versions_valid_from'), ['valid_from'], unique=False)

    op.create_table('task_steps',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('preconditions', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_steps_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_steps_task_id'), ['task_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_seq'), ['seq'], unique=False)

    op.create_table('world_diffs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('baseline_timestamp', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True),
    sa.Column('target_timestamp', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_diffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_diffs_seq'), ['seq'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_diffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_diffs_seq'))

    op.drop_table('world_diffs')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_seq'))

    op.drop_table('tasks')
    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_steps_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_steps_seq'))

    op.drop_table('task_steps')
    with op.batch_alter_table('state_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_versions_valid_from'))
        batch_op.drop_index(batch_op.f('ix_state_versions_seq'))
        batch_op.drop_index(batch_op.f('ix_state_versions_entity_id'))
        batch_op.drop_index(batch_op.f('ix_state_versions_attribute'))

    op.drop_table('state_versions')
    with op.batch_alter_table('search_coverage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_coverage_timestamp'))
        batch_op.drop_index(batch_op.f('ix_search_coverage_seq'))
        batch_op.drop_index(batch_op.f('ix_search_coverage_region'))

    op.drop_table('search_coverage')
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relations_target_entity'))
        batch_op.drop_index(batch_op.f('ix_relations_source_entity'))
        batch_op.drop_index(batch_op.f('ix_relations_seq'))

    op.drop_table('relations')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_observations_session_id'))
        batch_op.drop_index(batch_op.f('ix_observations_seq'))

    op.drop_table('observations')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_timestamp'))
        batch_op.drop_index(batch_op.f('ix_evidence_source_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_source_reference'))
        batch_op.drop_index(batch_op.f('ix_evidence_seq'))

    op.drop_table('evidence')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_events_seq'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_entity_id'))

    op.drop_table('events')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_type'))
        batch_op.drop_index(batch_op.f('ix_entities_seq'))
        batch_op.drop_index(batch_op.f('ix_entities_anchor'))

    op.drop_table('entities')
    # ### end Alembic commands ###
