"""anchors sessions identity resolution

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 15:56:13.159631
"""
from alembic import op
import sqlalchemy as sa
import backend.app.repositories.sql.tables


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchors',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('anchor_type', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=128), nullable=True),
    sa.Column('frame', sa.JSON(), nullable=False),
    sa.Column('created_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anchors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anchors_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anchors_seq'), ['seq'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('started_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('ended_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True),
    sa.Column('last_observation_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_started_at'), ['started_at'], unique=False)

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity_status', sa.String(length=32), server_default='ESTABLISHED', nullable=False))
        batch_op.add_column(sa.Column('identity_candidates', sa.JSON(), server_default='[]', nullable=False))

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolutions', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('resolutions')

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_column('identity_candidates')
        batch_op.drop_column('identity_status')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_sessions_seq'))

    op.drop_table('sessions')
    with op.batch_alter_table('anchors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anchors_seq'))
        batch_op.drop_index(batch_op.f('ix_anchors_parent_id'))

    op.drop_table('anchors')
    # ### end Alembic commands ###
