"""evidence engine

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 16:11:06.650155
"""
from alembic import op
import sqlalchemy as sa
import backend.app.repositories.sql.tables


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_dependencies',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('dependent_entity_id', sa.String(length=128), nullable=False),
    sa.Column('dependent_attribute', sa.String(length=128), nullable=False),
    sa.Column('depends_on_entity_id', sa.String(length=128), nullable=False),
    sa.Column('depends_on_attribute', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_dependencies_dependent_entity_id'), ['dependent_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_dependencies_depends_on_entity_id'), ['depends_on_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_dependencies_seq'), ['seq'], unique=False)

    op.create_table('conflicts',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('attribute', sa.String(length=128), nullable=False),
    sa.Column('version_ids', sa.JSON(), nullable=False),
    sa.Column('opened_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('resolved_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True),
    sa.Column('resolution_version_id', sa.String(length=128), nullable=True),
    sa.Column('resolution_evidence', sa.String(length=128), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_attribute'), ['attribute'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_seq'), ['seq'], unique=False)

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=64), nullable=True))

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=128), server_default='unknown', nullable=False))
        batch_op.add_column(sa.Column('content', sa.JSON(), server_default='{}', nullable=False))

    with op.batch_alter_table('state_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disposition', sa.String(length=32), server_default='ACCEPTED', nullable=False))
        batch_op.add_column(sa.Column('support', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('last_supported_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_validated_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('volatility_class', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('invalidated_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True))

    # ### end Alembic commands ###
    _migrate_data()


# Frozen copy of the source mapping at revision 0003 (migrations must not depend on
# application code that may change later).
_SOURCE_MAP = {
    "camera": "VISUAL_OBSERVATION", "webcam": "VISUAL_OBSERVATION", "phone_camera": "VISUAL_OBSERVATION",
    "overhead_camera": "VISUAL_OBSERVATION", "visual_label": "VISUAL_OBSERVATION", "sensor": "SENSOR_READING",
    "microphone": "AUDIO_OBSERVATION", "digital_registry": "EXTERNAL_RECORD", "authoritative_record": "EXTERNAL_RECORD",
    "manual_verification": "MANUAL_VERIFICATION", "manual_registration": "USER_STATEMENT", "user": "USER_STATEMENT",
    "procedure": "PROCEDURE", "system": "SYSTEM_EVENT",
}


def _migrate_data() -> None:
    """Free-text evidence.source_type → SourceType enum (old value kept in `source`);
    state versions get support refs and derived statuses moved out of `status`."""
    conn = op.get_bind()
    ev = sa.table("evidence", sa.column("id"), sa.column("source_type"), sa.column("source"),
                  sa.column("timestamp"), sa.column("quality"), sa.column("authority"))
    sv = sa.table("state_versions", sa.column("id"), sa.column("status"), sa.column("disposition"),
                  sa.column("valid_from"), sa.column("supported_by", sa.JSON), sa.column("support", sa.JSON),
                  sa.column("last_supported_at"))
    evidence = {}
    for row in conn.execute(sa.select(ev)).fetchall():
        old = row.source_type
        new = _SOURCE_MAP.get(old.lower(), old.upper() if old.isupper() else "OTHER")
        conn.execute(ev.update().where(ev.c.id == row.id).values(source_type=new, source=old))
        evidence[row.id] = {"at": str(row.timestamp), "source": old, "source_type": new,
                            "strength": float(row.quality) * float(row.authority)}
    for row in conn.execute(sa.select(sv)).fetchall():
        support = [dict(evidence_id=e, **evidence[e]) for e in (row.supported_by or []) if e in evidence]
        status, disposition = row.status, "ACCEPTED"
        if status == "STALE":
            status = "OBSERVED"  # staleness is now derived at read time
        elif status == "CONTRADICTED":
            status, disposition = "OBSERVED", "CONFLICTING"
        conn.execute(sv.update().where(sv.c.id == row.id).values(
            support=support, status=status, disposition=disposition, last_supported_at=row.valid_from))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state_versions', schema=None) as batch_op:
        batch_op.drop_column('invalidated_at')
        batch_op.drop_column('volatility_class')
        batch_op.drop_column('last_validated_at')
        batch_op.drop_column('last_supported_at')
        batch_op.drop_column('support')
        batch_op.drop_column('disposition')

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('source')

    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_seq'))
        batch_op.drop_index(batch_op.f('ix_conflicts_opened_at'))
        batch_op.drop_index(batch_op.f('ix_conflicts_entity_id'))
        batch_op.drop_index(batch_op.f('ix_conflicts_attribute'))

    op.drop_table('conflicts')
    with op.batch_alter_table('claim_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_dependencies_seq'))
        batch_op.drop_index(batch_op.f('ix_claim_dependencies_depends_on_entity_id'))
        batch_op.drop_index(batch_op.f('ix_claim_dependencies_dependent_entity_id'))

    op.drop_table('claim_dependencies')
    # ### end Alembic commands ###
