"""memory core tasks hypotheses

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 16:17:00.644442
"""
from alembic import op
import sqlalchemy as sa
import backend.app.repositories.sql.tables


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causal_hypotheses',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('cause_event_id', sa.String(length=128), nullable=True),
    sa.Column('effect_event_id', sa.String(length=128), nullable=True),
    sa.Column('entity_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('epistemic_status', sa.String(length=32), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('causal_hypotheses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_causal_hypotheses_seq'), ['seq'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_status', sa.String(length=32), server_default='UNKNOWN', nullable=False))
        batch_op.add_column(sa.Column('postconditions', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('started_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_by', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('invalidated_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('procedure_entity_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('procedure_revision', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('interruptions', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('last_verified_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True))

    # ### end Alembic commands ###
    _migrate_steps()


def _migrate_steps() -> None:
    """TaskStep.status held an epistemic status; split it into progress + completion grade."""
    conn = op.get_bind()
    steps = sa.table("task_steps", sa.column("id"), sa.column("status"), sa.column("completion_status"),
                     sa.column("preconditions", sa.JSON))
    progress = {"VERIFIED": "COMPLETED", "OBSERVED": "COMPLETED", "STALE": "NEEDS_REVERIFICATION"}
    for row in conn.execute(sa.select(steps)).fetchall():
        if row.status in ("PENDING", "IN_PROGRESS", "COMPLETED", "BLOCKED", "NEEDS_REVERIFICATION", "SKIPPED"):
            continue
        completion = row.status if row.status in ("VERIFIED", "OBSERVED", "STALE") else "UNKNOWN"
        pre = row.preconditions if isinstance(row.preconditions, list) else []
        conn.execute(steps.update().where(steps.c.id == row.id).values(
            status=progress.get(row.status, "PENDING"), completion_status=completion, preconditions=pre))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('last_verified_at')
        batch_op.drop_column('interruptions')
        batch_op.drop_column('procedure_revision')
        batch_op.drop_column('procedure_entity_id')
        batch_op.drop_column('assigned_to')

    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.drop_column('invalidated_reason')
        batch_op.drop_column('completed_by')
        batch_op.drop_column('started_at')
        batch_op.drop_column('postconditions')
        batch_op.drop_column('completion_status')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_task_id'))
        batch_op.drop_column('task_id')

    with op.batch_alter_table('causal_hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_causal_hypotheses_seq'))

    op.drop_table('causal_hypotheses')
    # ### end Alembic commands ###
