"""world diff and search coverage

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-01 16:26:05.612789
"""
from alembic import op
import sqlalchemy as sa
import backend.app.repositories.sql.tables


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_coverage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=128), server_default='unknown', nullable=False))
        batch_op.add_column(sa.Column('session_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('coverage_fraction', sa.Float(), server_default='1.0', nullable=False))
        batch_op.add_column(sa.Column('found', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('confirmed_absent', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('inconclusive', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('policy', sa.String(length=64), server_default='coverage-v1', nullable=False))
        batch_op.create_index(batch_op.f('ix_search_coverage_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('world_diffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=32), server_default='snapshot', nullable=False))
        batch_op.add_column(sa.Column('uncertain', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_diffs', schema=None) as batch_op:
        batch_op.drop_column('uncertain')
        batch_op.drop_column('mode')

    with op.batch_alter_table('search_coverage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_coverage_session_id'))
        batch_op.drop_column('policy')
        batch_op.drop_column('inconclusive')
        batch_op.drop_column('confirmed_absent')
        batch_op.drop_column('found')
        batch_op.drop_column('coverage_fraction')
        batch_op.drop_column('session_id')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
