"""actions principals outcomes

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-01 16:41:59.629764
"""
from alembic import op
import sqlalchemy as sa
import backend.app.repositories.sql.tables


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_entity_ids', sa.JSON(), nullable=False),
    sa.Column('consequential', sa.Boolean(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('expected_outcome', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prerequisite_checks', sa.JSON(), nullable=False),
    sa.Column('outcome_checks', sa.JSON(), nullable=False),
    sa.Column('requested_observations', sa.JSON(), nullable=False),
    sa.Column('authorization', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.String(length=128), nullable=True),
    sa.Column('performed_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('step_id', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('updated_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_status'), ['status'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('observed', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('performed_by', sa.String(length=128), nullable=True),
    sa.Column('recorded_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcomes_seq'), ['seq'], unique=False)

    op.create_table('principals',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('entity_scope', sa.JSON(), nullable=True),
    sa.Column('created_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_principals_seq'), ['seq'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_principals_seq'))

    op.drop_table('principals')
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_seq'))
        batch_op.drop_index(batch_op.f('ix_outcomes_action_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_status'))
        batch_op.drop_index(batch_op.f('ix_actions_seq'))

    op.drop_table('actions')
    # ### end Alembic commands ###
