"""observation redaction

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-01 17:14:41.200224
"""
from alembic import op
import sqlalchemy as sa
import backend.app.repositories.sql.tables


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redaction', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('redaction')

    # ### end Alembic commands ###
