"""risk levels

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-02 23:31:52.347149
"""
from alembic import op
import sqlalchemy as sa
import backend.app.repositories.sql.tables


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk', sa.String(length=16), server_default='MEDIUM', nullable=False))

    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk', sa.String(length=16), server_default='MEDIUM', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.drop_column('risk')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('risk')

    # ### end Alembic commands ###
