"""identity curation

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-03 11:03:48.058367
"""
from alembic import op
import sqlalchemy as sa
import backend.app.repositories.sql.tables


revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_merges',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('merged_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_version_ids', sa.JSON(), nullable=False),
    sa.Column('target_version_ids', sa.JSON(), nullable=False),
    sa.Column('source_identity_status', sa.String(length=32), nullable=False),
    sa.Column('source_identity_candidates', sa.JSON(), nullable=False),
    sa.Column('moved_relation_ids', sa.JSON(), nullable=False),
    sa.Column('undone_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True),
    sa.Column('undone_by', sa.String(length=128), nullable=True),
    sa.Column('undo_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity_merges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_merges_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_merges_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_merges_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True))

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merged_into', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('merged_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('distinct_from', sa.JSON(), server_default='[]', nullable=False))
        batch_op.create_index(batch_op.f('ix_entities_merged_into'), ['merged_into'], unique=False)

    with op.batch_alter_table('state_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('retired_at', backend.app.repositories.sql.tables.UTCDateTimeType(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state_versions', schema=None) as batch_op:
        batch_op.drop_column('retired_at')
        batch_op.drop_column('recorded_at')

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_merged_into'))
        batch_op.drop_column('distinct_from')
        batch_op.drop_column('merged_at')
        batch_op.drop_column('merged_into')

    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_column('recorded_at')

    with op.batch_alter_table('identity_merges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_merges_target_id'))
        batch_op.drop_index(batch_op.f('ix_identity_merges_source_id'))
        batch_op.drop_index(batch_op.f('ix_identity_merges_seq'))

    op.drop_table('identity_merges')
    # ### end Alembic commands ###
